#!/bin/bash

BG="#122229"
FG="#d29a3d"

FONT1="dweep:size=8"
FONT2="siji:size=8"

PW=256
PH=24
PX=555
PY=372

echo "%{c}  %{A:l:}logout%{A}  %{A:p:}shutdown%{A}  %{A:r:}reboot%{A}  %{A:s:}suspend%{A}  %{A:b:}close%{A}  " | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT1" -f "$FONT2" -B "$BG" -F "$FG" -p | \
    while :; do
        read line
        case $line in 
            'b')
                p=$(pgrep -n lemonbar)
                kill $p 
                exit 
                ;;
            's')
                systemctl suspend &
                p=$(pgrep -n lemonbar)
                kill $p 
                exit                
                ;;
            'p')
                shutdown now
                exit
                ;;
            'r')
                reboot
                exit
                ;;
	    			'l')
								pkill -x panel; pkill mpd; bspc quit
								exit
								;;

        esac
    done
