#! /bin/sh
#
# Example panel for LemonBoy's bar

. ~/.config/bspwm/panel/panel_colors

num_mon=$(bspc query -M | wc -l)
PADDING="  "

while read -r line ; do
	case $line in
		D*)
			# date output
			date="$PADDING${line#?}$PADDING"
			;;
		R*)
		 	# music info
		 	music="%{B$background}%{F$foreground}$PADDING${line#?}$PADDING%{F-}%{B-}"
		 	;;
		C*)
			# clock output
			clock="$PADDING${line#?}$PADDING"
			;;

		B*)
			# battery percent output
			battery="%{A:bat.sh:}$PADDING${line#?}$PADDING%{A}"
			;;

		V*)
			# alsa volume
			volume="$PADDING${line#?}$PADDING"
			;;
		L*)
			# wifi link
      wifi="$PADDING${line#?}$PADDING"
			;;
		P*)
			# power
      power="%{A:bspc quit && pkill panel && pkill mpd:}$PADDING${line#?}$PADDING%{A}"
			;;

		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$red1}%{B$background}$PADDING${name}$PADDING%{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG}$PADDING${name}$PADDING%{B-}%{F-}  "
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$foreground}%{B$black1}%{U$black1}%{+u}$PADDING${name}$PADDING%{-u}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$background}%{B$black1}%{U$black1}%{+u}$PADDING${name}$PADDING%{-u}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$urgent}%{B$lack1}%{U$black1}%{+u}$PADDING${name}$PADDING%{-u}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$foreground}%{B$background}%{A:bspc desktop -f ${name}:}$PADDING${name}$PADDING%{A}%{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$black1}%{B$background}%{A:bspc desktop -f ${name}:}$PADDING${name}$PADDING%{A}%{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$foreground}%{B$urgent}$PADDING${name}$PADDING%{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
    printf "%s\n" "%{l}${music}%{c}${wm_infos}%{r}${wifi}${volume}${battery}${clock}"
done
