#! /bin/sh

sxhkd &

bspc config border_width         1
bspc config window_gap           14
bspc config top_padding          26
bspc config left_padding         8
bspc config right_padding        8
bspc config bottom_padding       8

bspc config normal_border_color '#2b3135'
bspc config focused_border_color '#4c5356'
bspc config presel_feedback_color '#2b3135'


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d     

# Use xprop to find names
bspc rule -a Firefox desktop=^2
bspc rule -a Nitrogen state=floating
bspc rule -a Colorgrab state=floating
bspc rule -a Arandr state=floating
bspc rule -a Bleachbit state=floating
bspc rule -a Thunar desktop=^3 state=floating
bspc rule -a Dialog desktop=^2

$HOME/.config/bspwm/panel/panel &
